function [road, centreline] = setupRoad()

    %%%%%%%%%%%%%%%%%%%%%%
    %%% Road setup
    road = struct();
    road.centreLineWidth = 0.05;
    road.drawDist = 80;
    road.laneWidth = 2.5;
    road.totalWidth = road.laneWidth*2;                                                     % RSA local road standard
    road.vertexCoords = single([-road.laneWidth, 0, 0, ...
                                road.laneWidth, 0, 0, ...
                                road.laneWidth, road.drawDist, 0, ...
                                -road.laneWidth, road.drawDist, 0]);                        % coOrds for each vertex
    road.vertexColors = single([0.29, 0.29,	0.31, ...
                                0.29, 0.29,	0.31, ...
                                0.29, 0.29,	0.31, ...
                                0.29, 0.29,	0.31]);                                                    % colours at each vertex
    road.elementArray = int32([0, 1, 2, 3]);                                                % vertex numbers for the faces

    %%%%%%%%%%%%%%%%%%%%%%
    %%% Centre line setup
    centreline = struct();
    centreline.width = 0.15;
    centreline.length = 3;
    centreline.y = 0:centreline.length*2:road.drawDist;
    centreline.vertexCoords = single([-centreline.width/2, 0, 0.01, ...
                                centreline.width/2, 0, 0.01, ...
                                centreline.width/2, centreline.length, 0.01, ...
                                -centreline.width/2, centreline.length, 0.01]);                        % coOrds for each vertex
    centreline.vertexColors = single([1,  1,  1, ...
                                1,  1,	1, ...
                                1,  1,	1, ...
                                1,  1,	1]);                                                    % colours at each vertex
    centreline.elementArray = int32([0, 1, 2, 3]);                                                % vertex numbers for the faces

    
end
